services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics
    container_name: victoria-metrics
    ports:
      - "8428:8428" # Exposes the web UI and API on localhost:8428
    volumes:
      - ./victoria-metrics-data:/vm-data
    command: 
      - '--retentionPeriod=30d' # Adjust retention as needed