all:
  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            master-1:
              ansible_host: 10.0.1.10
              ip: 10.0.1.10
            master-2:
              ansible_host: 10.0.1.11
              ip: 10.0.1.11
            master-3:
              ansible_host: 10.0.1.12
              ip: 10.0.1.12
        worker_nodes:
          hosts:
            worker-1:
              ansible_host: 10.0.2.10
              ip: 10.0.2.10
            worker-2:
              ansible_host: 10.0.2.11
              ip: 10.0.2.11
            worker-3:
              ansible_host: 10.0.2.12
              ip: 10.0.2.12
        etcd:
          hosts:
            master-1:
              ansible_host: 10.0.1.10
              ip: 10.0.1.10
            master-2:
              ansible_host: 10.0.1.11
              ip: 10.0.1.11
            master-3:
              ansible_host: 10.0.1.12
              ip: 10.0.1.12
    monitoring:
      hosts:
        prometheus-server:
          ansible_host: 10.0.3.10
        grafana-server:
          ansible_host: 10.0.3.11

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/metricflow-key.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'