app:
  name: MetricFlow
  version: "1.0.0"
  environment: production
  
server:
  host: "0.0.0.0"
  port: 8080
  workers: 4

redis:
  host: redis
  port: 6379
  db: 0

monitoring:
  metrics_interval: 30
  retention_hours: 24

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"